### ISSUE TITLE
Character gets stuck in animation if walking during attack

### ISSUE THREAD

**Issue by Flynsarmy** [Snaiel/Godot4ThirdPersonCombatPrototype#1]
Steps to replicate:
* Hold W
* Wait a bit to start walking then left click
* Let go of everything

https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/334808/5fd03268-f711-443a-91a1-19d97d606e00

**Comment by Snaiel** [comment]
I can't seem to replicate it. Does it happen every time whenever the steps you described are carried out?
