### ISSUE TITLE
improve player stun after full instability

### ISSUE THREAD

**Issue by Snaiel** [Snaiel/Godot4ThirdPersonCombatPrototype#15]
#10 thx for initial implementation

- make instability reach maximum, then stun player on next hit.
- sfx
- player kneel?
- instability meter animation then reset
- camera shake? (need to see where else to implement, not too much tho)
- fix getting hit sound straight after getting stunned

**Comment by Sod3n** [comment]
- "_fix getting hit sound straight after getting stunned_" - actually just need to change resource of stun sound node (its currently use hit sound) to something suitable
