### ISSUE TITLE
Scene file 'Main.tcsn' appears to be invalid/corrupt, Error while loading file 'Main.tcsn', Broken dependencies

### ISSUE THREAD

**Issue by Snaiel** [Snaiel/Godot4ThirdPersonCombatPrototype#3]
![image](https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/56014779/cd6c64ca-a685-4ed4-b3f3-10626bf75706)

This occurs because you do not have Blender imports configured with Godot. See the documentation on Blender imports in Godot here: https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_scenes.html#importing-blend-files-directly-within-godot

In order to load the project, you must install Blender https://www.blender.org/ as this is what's used for the 3d models. The models are meant to be automatically loaded in using Blender within Godot but this needs to be configured.

After installing Blender, locate the install directory. For example, here is the location for my Blender on Linux:
![image](https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/56014779/beb691a5-8349-48b9-a6ab-80967cb04606)

Blender locations for Linux, Windows, Mac are documented here: https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html

Once you have identified your blender install path, go to the **Editor** option in the top left menu in Godot. Then select **Editor Settings**
![image](https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/56014779/f31be85b-4280-4833-b856-8c431e9bfb59)

Then go to **FileSystem > Import** and paste your Blender path into **Blender 3 Path**.
![image](https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/56014779/c711bd93-6df1-4dcd-a4e4-938dabe7fe4e)

Afterwards, just reload the project and it should work now.
![image](https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/56014779/446a84ff-1dbf-4822-9cfd-4b8d38fd2dea)

**Comment by Snaiel** [comment]
This is the error that shows when opening the project in Godot 4.2 without enabling blender imports.

![image](https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/56014779/d91b512d-e60a-40f5-8069-17f0d0fc6791)

**Comment by IRLadderGoat** [comment]
As an extension, there might be problems with the newest version of blender. 
Had a similar experience to https://github.com/godotengine/godot/issues/92365.
Diagnosed in https://github.com/godotengine/godot/pull/93998.
