### ISSUE TITLE
Broken Dependencies/Broken scenes

### ISSUE THREAD

**Issue by miguelnassif3** [Snaiel/Godot4ThirdPersonCombatPrototype#38]
![screenshot1](https://github.com/Snaiel/Godot4ThirdPersonCombatPrototype/assets/52503085/80617adc-bc59-4057-ba75-883d00929952)

Hello. I'm not quite sure if this is a problem on my end but I tried to clone this project to play around with and learn but it seems that there are a few broken dependencies in a few of the entities and animation scenes.

**Comment by Snaiel** [comment]
thanks for bringing this up. I'll dig into this as soon as possible.

What version of Godot are you using? The project is using 4.2.2 currently so if you're not already on the same version that might be a good place to start.

Have you got Blender Imports configured in the editor settings? See #3

**Comment by Snaiel** [comment]
@miguelnassif3

I just checked and the problem is that Blender Imports are not configured in your editor settings. See #3
